### ISSUE TITLE
Desarrollo de formulario de HTML (Contact)

### ISSUE THREAD

**Issue by DiegoBP12** [MarioAlbertoNL1799/Proyecto_final_3ro#12]

**Comment by MarioAlbertoNL1799** [comment]
Formulario está elaborado acorde el Mockup #8  de contacto, las funciones de los botones falta por anexar.

**Comment by MarioAlbertoNL1799** [comment]
El formulario está integrado a la página principal y adjuntado a la sección de [https://github.com/MarioAlbertoNL1799/Proyecto_final_3ro/tree/master/Proyecto_web](url)
